package runtime

import (
	"fmt"
	"sort"
	"strings"

	"github.com/okedeji/agentcage/internal/agentfile"
)

// dockerfileInput is the parameter object for generateDockerfile.
type dockerfileInput struct {
	Agentfile *agentfile.Agentfile

	// Labels are written as OCI image labels so external tools
	// (`nerdctl inspect`, registry UIs) can read the agent's provenance
	// without unpacking the bundle. Empty values are skipped.
	Labels map[string]string
}

// generateDockerfile produces the Dockerfile string that BuildKit's
// dockerfile.v0 frontend will parse. The Agentfile directives (FROM, RUN,
// ENV) pass through unchanged; the only real translation is on ENTRYPOINT,
// which becomes the JSON-array form:
//
//	ENTRYPOINT cmd → ENTRYPOINT ["sh", "-c", "cmd"]
//
// On top of the author's input, the codegen injects:
//
//   - WORKDIR /agent
//   - COPY . /agent (bundle's source tree)
//   - OCI labels for spec_version, files_hash, built_with, built_at so
//     the image carries the bundle's provenance
//
// The output is deterministic. Given the same Agentfile and the same
// labels map, this returns byte-identical bytes, important because
// BuildKit's cache key hashes the input.
func generateDockerfile(in dockerfileInput) string {
	af := in.Agentfile
	var b strings.Builder

	fmt.Fprintf(&b, "# Auto-generated by agentcage. Do not edit.\n")
	fmt.Fprintf(&b, "# syntax=docker/dockerfile:1\n\n")

	fmt.Fprintf(&b, "FROM %s\n", af.From)
	fmt.Fprintf(&b, "WORKDIR /agent\n")

	// RUNs come BEFORE the source COPY. The common case is
	// "RUN pip install mcp anthropic", a dependency
	// declaration whose inputs are entirely in the line itself,
	// not in the agent's source tree. Putting RUN first means
	// editing agent.py only busts the cheap COPY layer, not the
	// expensive pip install. Build times after the first one stay
	// in the seconds-not-minutes range.
	//
	// Trade-off: this breaks "RUN pip install -r requirements.txt"
	// (and equivalent Node / Cargo patterns) because the file is
	// not in the image yet when RUN executes. Authors that need
	// that pattern either inline the deps in RUN (the agentcage
	// convention) or, when M2 ships smarter codegen, declare a
	// dependency-manifest file explicitly.
	for _, cmd := range af.Run {
		fmt.Fprintf(&b, "RUN %s\n", cmd)
	}

	// COPY the agent's source tree last so changes to it only
	// invalidate cache from this layer onward, not the RUN layers
	// above.
	fmt.Fprintf(&b, "COPY . /agent\n")

	// ENV is ordered for determinism. BuildKit cares about the order
	// only for the cache key, not for runtime semantics, but a stable
	// order makes the cache stable across rebuilds with the same input.
	keys := sortedKeys(af.Env)
	for _, k := range keys {
		// An empty value is an operator-required input with no default, not a
		// default of empty. Baking it would mask the fail-closed check, so the
		// runtime injects it from the operator pool instead.
		if af.Env[k] == "" {
			continue
		}
		fmt.Fprintf(&b, "ENV %s=%s\n", k, dockerfileEscapeEnv(af.Env[k]))
	}

	// OCI image labels for provenance. LABEL keys are namespaced under
	// io.agentcage.* so they do not collide with conventional OCI image
	// labels (org.opencontainers.image.* etc).
	for _, k := range sortedKeys(in.Labels) {
		v := in.Labels[k]
		if v == "" {
			continue
		}
		fmt.Fprintf(&b, "LABEL %s=%s\n", k, dockerfileQuote(v))
	}

	// ENTRYPOINT goes last by convention. Using shell form (sh -c "...")
	// because the Agentfile's ENTRYPOINT is a single command string,
	// not a JSON array. Shell form interprets it identically to how a
	// shell would.
	fmt.Fprintf(&b, "ENTRYPOINT [\"sh\", \"-c\", %s]\n", dockerfileQuote(af.Entrypoint))

	return b.String()
}

func sortedKeys(m map[string]string) []string {
	if len(m) == 0 {
		return nil
	}
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// dockerfileQuote produces a JSON-string-quoted form of s, the shape
// the Dockerfile parser accepts for LABEL values and JSON-form ENTRYPOINT
// arguments. Uses Go's strconv via fmt's %q verb which is exactly
// JSON-string syntax for ASCII content.
func dockerfileQuote(s string) string {
	return fmt.Sprintf("%q", s)
}

// dockerfileEscapeEnv handles the rare case where an ENV value contains
// whitespace or special characters. Dockerfile's KEY=value form treats
// the value as a string until newline, so we only need to escape
// backslashes and wrap in quotes when whitespace is present.
func dockerfileEscapeEnv(v string) string {
	if !strings.ContainsAny(v, " \t\"\\") {
		return v
	}
	return dockerfileQuote(v)
}
