package runtime

import (
	"fmt"
	"strings"
)

// LimaTemplateInput drives generateLimaTemplate.
type LimaTemplateInput struct {
	// InstanceName is the Lima VM name; agentcage uses one shared instance
	// per host.
	InstanceName string

	// HostSocketDir receives the forwarded in-VM Unix sockets. It must exist
	// before `limactl start` runs; the YAML uses absolute paths so Lima does
	// not try to expand $HOME inside the value.
	HostSocketDir string

	// CPUs, MemoryGiB, and DiskSizeGiB cap the VM; zero applies the defaults
	// below.
	CPUs        int
	MemoryGiB   int
	DiskSizeGiB int
}

// The 8 GiB memory default is what the cage caps and live-cage counts are
// sized against (resources.go, config.go); 4 forced the memory clamp to
// shrink almost every multi-cage run.
const (
	defaultLimaCPUs        = 4
	defaultLimaMemoryGiB   = 8
	defaultLimaDiskSizeGiB = 60
)

// generateLimaTemplate produces the YAML `limactl create` consumes: Lima's
// stock ubuntu-lts base with rootless containerd, forwarding the containerd
// and buildkitd sockets back to the host. Output is byte-deterministic for
// the same input; Lima recreates the VM when the template hash changes, so a
// spurious diff means a spurious recreation. Rootless matches Lima's stock
// buildkit.yaml; lifting it would require system: true and `lima sudo` for
// every nerdctl call.
func generateLimaTemplate(in LimaTemplateInput) string {
	cpus := in.CPUs
	if cpus <= 0 {
		cpus = defaultLimaCPUs
	}
	mem := in.MemoryGiB
	if mem <= 0 {
		mem = defaultLimaMemoryGiB
	}
	disk := in.DiskSizeGiB
	if disk <= 0 {
		disk = defaultLimaDiskSizeGiB
	}

	var b strings.Builder

	fmt.Fprintln(&b, "# Auto-generated by agentcage. Do not edit.")
	fmt.Fprintln(&b, "# Provisions a Linux VM with rootless containerd + buildkitd,")
	fmt.Fprintln(&b, "# forwarding both daemon sockets back to the host.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "minimumLimaVersion: 2.0.0")
	fmt.Fprintln(&b, "base: template:_images/ubuntu-lts")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "cpus: %d\n", cpus)
	fmt.Fprintf(&b, "memory: %dGiB\n", mem)
	fmt.Fprintf(&b, "disk: %dGiB\n", disk)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "containerd:")
	fmt.Fprintln(&b, "  system: false")
	fmt.Fprintln(&b, "  user: true")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "portForwards:")
	// Same in-guest paths as Lima's stock buildkit.yaml, matching the
	// rootless setup the base template installs.
	fmt.Fprintln(&b, "- guestSocket: \"/run/user/{{.UID}}/buildkit-default/buildkitd.sock\"")
	fmt.Fprintf(&b, "  hostSocket: %q\n", in.HostSocketDir+"/buildkitd.sock")
	fmt.Fprintln(&b, "- guestSocket: \"/run/user/{{.UID}}/containerd/containerd.sock\"")
	fmt.Fprintf(&b, "  hostSocket: %q\n", in.HostSocketDir+"/containerd.sock")

	return b.String()
}
