package runtime

import (
	"fmt"
	"strings"
)

// LimaTemplateInput drives generateLimaTemplate.
type LimaTemplateInput struct {
	// InstanceName is the Lima VM name (used to scope the LIMA_HOME path).
	// agentcage uses a single shared instance, "agentcage", for every
	// build on a given host.
	InstanceName string

	// HostSocketDir is where Lima will forward the in-VM Unix sockets to.
	// Typically ~/.agentcage/lima/sock. The directory must exist by the
	// time `limactl start` runs; the YAML uses absolute paths so Lima
	// itself does not try to expand $HOME or templates inside the value.
	HostSocketDir string

	// CPUs and MemoryGiB cap the VM's resources. Defaults are applied
	// when zero; see defaultLimaCPUs / defaultLimaMemoryGiB.
	CPUs        int
	MemoryGiB   int
	DiskSizeGiB int
}

const (
	defaultLimaCPUs        = 4
	defaultLimaMemoryGiB   = 4
	defaultLimaDiskSizeGiB = 60
)

// generateLimaTemplate produces the YAML that `limactl create` consumes
// to provision agentcage's VM. The template is intentionally minimal —
// it leans on Lima's stock `_images/ubuntu-lts` base and on the rootless
// containerd that the Lima provisioning scripts install. On top of that
// it forwards two Unix sockets back to the host:
//
//   - containerd.sock — so the agentcage runtime can drive containerd
//     (image lookup, container create, task spawn, stdio).
//   - buildkitd.sock — so BuildKit's Go client can submit Solve
//     requests for image builds from generated Dockerfiles.
//
// The output is deterministic: same input → byte-identical YAML, which
// matters because Lima will recreate the VM when the template hash
// changes, and we do not want spurious recreations.
//
// Both forwarded sockets target the rootless paths under
// /run/user/{{.UID}}, matching Lima's stock buildkit.yaml template
// (https://github.com/lima-vm/lima/blob/v2.1.2/templates/buildkit.yaml).
// Rootless is the default; lifting it would require system: true and
// `lima sudo` for every nerdctl call, which we do not need.
func generateLimaTemplate(in LimaTemplateInput) string {
	cpus := in.CPUs
	if cpus <= 0 {
		cpus = defaultLimaCPUs
	}
	mem := in.MemoryGiB
	if mem <= 0 {
		mem = defaultLimaMemoryGiB
	}
	disk := in.DiskSizeGiB
	if disk <= 0 {
		disk = defaultLimaDiskSizeGiB
	}

	var b strings.Builder

	fmt.Fprintln(&b, "# Auto-generated by agentcage. Do not edit.")
	fmt.Fprintln(&b, "# Provisions a Linux VM with rootless containerd + buildkitd,")
	fmt.Fprintln(&b, "# forwarding both daemon sockets back to the host.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "minimumLimaVersion: 2.0.0")
	fmt.Fprintln(&b, "base: template:_images/ubuntu-lts")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "cpus: %d\n", cpus)
	fmt.Fprintf(&b, "memory: %dGiB\n", mem)
	fmt.Fprintf(&b, "disk: %dGiB\n", disk)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "containerd:")
	fmt.Fprintln(&b, "  system: false")
	fmt.Fprintln(&b, "  user: true")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "portForwards:")
	// Lima's stock buildkit.yaml forwards the rootless buildkitd socket
	// from this exact in-guest path; using the same path keeps us
	// compatible with the rootless containerd setup the base template
	// installs by default.
	fmt.Fprintln(&b, "- guestSocket: \"/run/user/{{.UID}}/buildkit-default/buildkitd.sock\"")
	fmt.Fprintf(&b, "  hostSocket: %q\n", in.HostSocketDir+"/buildkitd.sock")
	fmt.Fprintln(&b, "- guestSocket: \"/run/user/{{.UID}}/containerd/containerd.sock\"")
	fmt.Fprintf(&b, "  hostSocket: %q\n", in.HostSocketDir+"/containerd.sock")

	return b.String()
}
