// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/assessment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssessmentStatus int32

const (
	AssessmentStatus_ASSESSMENT_STATUS_UNSPECIFIED            AssessmentStatus = 0
	AssessmentStatus_ASSESSMENT_STATUS_DISCOVERY              AssessmentStatus = 1
	AssessmentStatus_ASSESSMENT_STATUS_EXPLOITATION           AssessmentStatus = 2
	AssessmentStatus_ASSESSMENT_STATUS_VALIDATION             AssessmentStatus = 3
	AssessmentStatus_ASSESSMENT_STATUS_PENDING_REVIEW         AssessmentStatus = 4
	AssessmentStatus_ASSESSMENT_STATUS_APPROVED               AssessmentStatus = 5
	AssessmentStatus_ASSESSMENT_STATUS_REJECTED               AssessmentStatus = 6
	AssessmentStatus_ASSESSMENT_STATUS_FAILED                 AssessmentStatus = 7
	AssessmentStatus_ASSESSMENT_STATUS_UNREVIEWED             AssessmentStatus = 8
	AssessmentStatus_ASSESSMENT_STATUS_AWAITING_PLAN_APPROVAL AssessmentStatus = 9
	AssessmentStatus_ASSESSMENT_STATUS_PLAN_UNAPPROVED        AssessmentStatus = 10
)

// Enum value maps for AssessmentStatus.
var (
	AssessmentStatus_name = map[int32]string{
		0:  "ASSESSMENT_STATUS_UNSPECIFIED",
		1:  "ASSESSMENT_STATUS_DISCOVERY",
		2:  "ASSESSMENT_STATUS_EXPLOITATION",
		3:  "ASSESSMENT_STATUS_VALIDATION",
		4:  "ASSESSMENT_STATUS_PENDING_REVIEW",
		5:  "ASSESSMENT_STATUS_APPROVED",
		6:  "ASSESSMENT_STATUS_REJECTED",
		7:  "ASSESSMENT_STATUS_FAILED",
		8:  "ASSESSMENT_STATUS_UNREVIEWED",
		9:  "ASSESSMENT_STATUS_AWAITING_PLAN_APPROVAL",
		10: "ASSESSMENT_STATUS_PLAN_UNAPPROVED",
	}
	AssessmentStatus_value = map[string]int32{
		"ASSESSMENT_STATUS_UNSPECIFIED":            0,
		"ASSESSMENT_STATUS_DISCOVERY":              1,
		"ASSESSMENT_STATUS_EXPLOITATION":           2,
		"ASSESSMENT_STATUS_VALIDATION":             3,
		"ASSESSMENT_STATUS_PENDING_REVIEW":         4,
		"ASSESSMENT_STATUS_APPROVED":               5,
		"ASSESSMENT_STATUS_REJECTED":               6,
		"ASSESSMENT_STATUS_FAILED":                 7,
		"ASSESSMENT_STATUS_UNREVIEWED":             8,
		"ASSESSMENT_STATUS_AWAITING_PLAN_APPROVAL": 9,
		"ASSESSMENT_STATUS_PLAN_UNAPPROVED":        10,
	}
)

func (x AssessmentStatus) Enum() *AssessmentStatus {
	p := new(AssessmentStatus)
	*p = x
	return p
}

func (x AssessmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssessmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_assessment_proto_enumTypes[0].Descriptor()
}

func (AssessmentStatus) Type() protoreflect.EnumType {
	return &file_api_proto_assessment_proto_enumTypes[0]
}

func (x AssessmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssessmentStatus.Descriptor instead.
func (AssessmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{0}
}

type CageTypeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CageType               `protobuf:"varint,1,opt,name=type,proto3,enum=agentcage.cage.v1.CageType" json:"type,omitempty"`
	Defaults      *ResourceLimits        `protobuf:"bytes,2,opt,name=defaults,proto3" json:"defaults,omitempty"`
	MaxBatchSize  int32                  `protobuf:"varint,3,opt,name=max_batch_size,json=maxBatchSize,proto3" json:"max_batch_size,omitempty"`
	MaxDuration   *durationpb.Duration   `protobuf:"bytes,4,opt,name=max_duration,json=maxDuration,proto3" json:"max_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CageTypeConfig) Reset() {
	*x = CageTypeConfig{}
	mi := &file_api_proto_assessment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CageTypeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CageTypeConfig) ProtoMessage() {}

func (x *CageTypeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CageTypeConfig.ProtoReflect.Descriptor instead.
func (*CageTypeConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{0}
}

func (x *CageTypeConfig) GetType() CageType {
	if x != nil {
		return x.Type
	}
	return CageType_CAGE_TYPE_UNSPECIFIED
}

func (x *CageTypeConfig) GetDefaults() *ResourceLimits {
	if x != nil {
		return x.Defaults
	}
	return nil
}

func (x *CageTypeConfig) GetMaxBatchSize() int32 {
	if x != nil {
		return x.MaxBatchSize
	}
	return 0
}

func (x *CageTypeConfig) GetMaxDuration() *durationpb.Duration {
	if x != nil {
		return x.MaxDuration
	}
	return nil
}

type AssessmentConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CustomerId       string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Scope            *TargetScope           `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	CageTypeConfigs  []*CageTypeConfig      `protobuf:"bytes,3,rep,name=cage_type_configs,json=cageTypeConfigs,proto3" json:"cage_type_configs,omitempty"`
	TotalTokenBudget int64                  `protobuf:"varint,4,opt,name=total_token_budget,json=totalTokenBudget,proto3" json:"total_token_budget,omitempty"`
	MaxDuration      *durationpb.Duration   `protobuf:"bytes,5,opt,name=max_duration,json=maxDuration,proto3" json:"max_duration,omitempty"`
	Guidance         *Guidance              `protobuf:"bytes,8,opt,name=guidance,proto3" json:"guidance,omitempty"`
	SkipPaths        []string               `protobuf:"bytes,9,rep,name=skip_paths,json=skipPaths,proto3" json:"skip_paths,omitempty"`
	Tags             map[string]string      `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Notifications    *NotificationConfig    `protobuf:"bytes,12,opt,name=notifications,proto3" json:"notifications,omitempty"`
	Name             string                 `protobuf:"bytes,13,opt,name=name,proto3" json:"name,omitempty"`
	MaxTotalCages    int32                  `protobuf:"varint,14,opt,name=max_total_cages,json=maxTotalCages,proto3" json:"max_total_cages,omitempty"`
	MaxIterations    int32                  `protobuf:"varint,17,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	Environment      map[string]string      `protobuf:"bytes,18,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Workflow         *Workflow              `protobuf:"bytes,19,opt,name=workflow,proto3" json:"workflow,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AssessmentConfig) Reset() {
	*x = AssessmentConfig{}
	mi := &file_api_proto_assessment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentConfig) ProtoMessage() {}

func (x *AssessmentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentConfig.ProtoReflect.Descriptor instead.
func (*AssessmentConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{1}
}

func (x *AssessmentConfig) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AssessmentConfig) GetScope() *TargetScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *AssessmentConfig) GetCageTypeConfigs() []*CageTypeConfig {
	if x != nil {
		return x.CageTypeConfigs
	}
	return nil
}

func (x *AssessmentConfig) GetTotalTokenBudget() int64 {
	if x != nil {
		return x.TotalTokenBudget
	}
	return 0
}

func (x *AssessmentConfig) GetMaxDuration() *durationpb.Duration {
	if x != nil {
		return x.MaxDuration
	}
	return nil
}

func (x *AssessmentConfig) GetGuidance() *Guidance {
	if x != nil {
		return x.Guidance
	}
	return nil
}

func (x *AssessmentConfig) GetSkipPaths() []string {
	if x != nil {
		return x.SkipPaths
	}
	return nil
}

func (x *AssessmentConfig) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AssessmentConfig) GetNotifications() *NotificationConfig {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *AssessmentConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AssessmentConfig) GetMaxTotalCages() int32 {
	if x != nil {
		return x.MaxTotalCages
	}
	return 0
}

func (x *AssessmentConfig) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *AssessmentConfig) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *AssessmentConfig) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

// Workflow controls pipeline gates that are operator-toggleable but
// not part of attack guidance. Wrapped (not flat bools on
// AssessmentConfig) so future gates can be added without proto field
// churn.
type Workflow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// require_plan_approval=true (default) pauses the assessment after
	// discovery on a plan_approval intervention; false runs the
	// generated plan immediately.
	RequirePlanApproval bool `protobuf:"varint,1,opt,name=require_plan_approval,json=requirePlanApproval,proto3" json:"require_plan_approval,omitempty"`
	// identify_in_requests=true (default) injects an X-Agentcage-Pentest
	// header on every cage-originated request to the target, identifying
	// the traffic as authorized pentest activity. Set false for
	// adversarial-simulation engagements that deliberately test the
	// target's detection capability.
	IdentifyInRequests bool `protobuf:"varint,2,opt,name=identify_in_requests,json=identifyInRequests,proto3" json:"identify_in_requests,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_api_proto_assessment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{2}
}

func (x *Workflow) GetRequirePlanApproval() bool {
	if x != nil {
		return x.RequirePlanApproval
	}
	return false
}

func (x *Workflow) GetIdentifyInRequests() bool {
	if x != nil {
		return x.IdentifyInRequests
	}
	return false
}

// PlanProposal is the orchestrator-generated exploitation plan
// surfaced on a plan_approval intervention. Serialized as the
// intervention's context_data.
type PlanProposal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Goal            string                 `protobuf:"bytes,1,opt,name=goal,proto3" json:"goal,omitempty"`
	Summary         string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Actions         []*PlanAction          `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	EstimatedCages  int32                  `protobuf:"varint,4,opt,name=estimated_cages,json=estimatedCages,proto3" json:"estimated_cages,omitempty"`
	EstimatedTokens int64                  `protobuf:"varint,5,opt,name=estimated_tokens,json=estimatedTokens,proto3" json:"estimated_tokens,omitempty"`
	Notes           string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlanProposal) Reset() {
	*x = PlanProposal{}
	mi := &file_api_proto_assessment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanProposal) ProtoMessage() {}

func (x *PlanProposal) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanProposal.ProtoReflect.Descriptor instead.
func (*PlanProposal) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{3}
}

func (x *PlanProposal) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *PlanProposal) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PlanProposal) GetActions() []*PlanAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *PlanProposal) GetEstimatedCages() int32 {
	if x != nil {
		return x.EstimatedCages
	}
	return 0
}

func (x *PlanProposal) GetEstimatedTokens() int64 {
	if x != nil {
		return x.EstimatedTokens
	}
	return 0
}

func (x *PlanProposal) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type PlanAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	VulnClass     string                 `protobuf:"bytes,2,opt,name=vuln_class,json=vulnClass,proto3" json:"vuln_class,omitempty"`
	Objective     string                 `protobuf:"bytes,3,opt,name=objective,proto3" json:"objective,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanAction) Reset() {
	*x = PlanAction{}
	mi := &file_api_proto_assessment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanAction) ProtoMessage() {}

func (x *PlanAction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanAction.ProtoReflect.Descriptor instead.
func (*PlanAction) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{4}
}

func (x *PlanAction) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PlanAction) GetVulnClass() string {
	if x != nil {
		return x.VulnClass
	}
	return ""
}

func (x *PlanAction) GetObjective() string {
	if x != nil {
		return x.Objective
	}
	return ""
}

type NotificationConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webhook       string                 `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	OnFinding     bool                   `protobuf:"varint,2,opt,name=on_finding,json=onFinding,proto3" json:"on_finding,omitempty"`
	OnComplete    bool                   `protobuf:"varint,3,opt,name=on_complete,json=onComplete,proto3" json:"on_complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationConfig) Reset() {
	*x = NotificationConfig{}
	mi := &file_api_proto_assessment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationConfig) ProtoMessage() {}

func (x *NotificationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationConfig.ProtoReflect.Descriptor instead.
func (*NotificationConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{5}
}

func (x *NotificationConfig) GetWebhook() string {
	if x != nil {
		return x.Webhook
	}
	return ""
}

func (x *NotificationConfig) GetOnFinding() bool {
	if x != nil {
		return x.OnFinding
	}
	return false
}

func (x *NotificationConfig) GetOnComplete() bool {
	if x != nil {
		return x.OnComplete
	}
	return false
}

type Guidance struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	AttackSurface  *AttackSurfaceGuidance  `protobuf:"bytes,1,opt,name=attack_surface,json=attackSurface,proto3" json:"attack_surface,omitempty"`
	AttackStrategy *AttackStrategyGuidance `protobuf:"bytes,3,opt,name=attack_strategy,json=attackStrategy,proto3" json:"attack_strategy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Guidance) Reset() {
	*x = Guidance{}
	mi := &file_api_proto_assessment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Guidance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guidance) ProtoMessage() {}

func (x *Guidance) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guidance.ProtoReflect.Descriptor instead.
func (*Guidance) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{6}
}

func (x *Guidance) GetAttackSurface() *AttackSurfaceGuidance {
	if x != nil {
		return x.AttackSurface
	}
	return nil
}

func (x *Guidance) GetAttackStrategy() *AttackStrategyGuidance {
	if x != nil {
		return x.AttackStrategy
	}
	return nil
}

type AttackSurfaceGuidance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []string               `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	ApiSpecs      []string               `protobuf:"bytes,2,rep,name=api_specs,json=apiSpecs,proto3" json:"api_specs,omitempty"`
	LimitToListed bool                   `protobuf:"varint,3,opt,name=limit_to_listed,json=limitToListed,proto3" json:"limit_to_listed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackSurfaceGuidance) Reset() {
	*x = AttackSurfaceGuidance{}
	mi := &file_api_proto_assessment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackSurfaceGuidance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackSurfaceGuidance) ProtoMessage() {}

func (x *AttackSurfaceGuidance) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackSurfaceGuidance.ProtoReflect.Descriptor instead.
func (*AttackSurfaceGuidance) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{7}
}

func (x *AttackSurfaceGuidance) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *AttackSurfaceGuidance) GetApiSpecs() []string {
	if x != nil {
		return x.ApiSpecs
	}
	return nil
}

func (x *AttackSurfaceGuidance) GetLimitToListed() bool {
	if x != nil {
		return x.LimitToListed
	}
	return false
}

type AttackStrategyGuidance struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	KnownWeaknesses []string               `protobuf:"bytes,1,rep,name=known_weaknesses,json=knownWeaknesses,proto3" json:"known_weaknesses,omitempty"`
	Context         string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttackStrategyGuidance) Reset() {
	*x = AttackStrategyGuidance{}
	mi := &file_api_proto_assessment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackStrategyGuidance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackStrategyGuidance) ProtoMessage() {}

func (x *AttackStrategyGuidance) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackStrategyGuidance.ProtoReflect.Descriptor instead.
func (*AttackStrategyGuidance) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{8}
}

func (x *AttackStrategyGuidance) GetKnownWeaknesses() []string {
	if x != nil {
		return x.KnownWeaknesses
	}
	return nil
}

func (x *AttackStrategyGuidance) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type AssessmentStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalCages        int32                  `protobuf:"varint,1,opt,name=total_cages,json=totalCages,proto3" json:"total_cages,omitempty"`
	ActiveCages       int32                  `protobuf:"varint,2,opt,name=active_cages,json=activeCages,proto3" json:"active_cages,omitempty"`
	FindingsCandidate int32                  `protobuf:"varint,3,opt,name=findings_candidate,json=findingsCandidate,proto3" json:"findings_candidate,omitempty"`
	FindingsValidated int32                  `protobuf:"varint,4,opt,name=findings_validated,json=findingsValidated,proto3" json:"findings_validated,omitempty"`
	FindingsRejected  int32                  `protobuf:"varint,5,opt,name=findings_rejected,json=findingsRejected,proto3" json:"findings_rejected,omitempty"`
	TokensConsumed    int64                  `protobuf:"varint,6,opt,name=tokens_consumed,json=tokensConsumed,proto3" json:"tokens_consumed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AssessmentStats) Reset() {
	*x = AssessmentStats{}
	mi := &file_api_proto_assessment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentStats) ProtoMessage() {}

func (x *AssessmentStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentStats.ProtoReflect.Descriptor instead.
func (*AssessmentStats) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{9}
}

func (x *AssessmentStats) GetTotalCages() int32 {
	if x != nil {
		return x.TotalCages
	}
	return 0
}

func (x *AssessmentStats) GetActiveCages() int32 {
	if x != nil {
		return x.ActiveCages
	}
	return 0
}

func (x *AssessmentStats) GetFindingsCandidate() int32 {
	if x != nil {
		return x.FindingsCandidate
	}
	return 0
}

func (x *AssessmentStats) GetFindingsValidated() int32 {
	if x != nil {
		return x.FindingsValidated
	}
	return 0
}

func (x *AssessmentStats) GetFindingsRejected() int32 {
	if x != nil {
		return x.FindingsRejected
	}
	return 0
}

func (x *AssessmentStats) GetTokensConsumed() int64 {
	if x != nil {
		return x.TokensConsumed
	}
	return 0
}

type AssessmentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId  string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Status        AssessmentStatus       `protobuf:"varint,3,opt,name=status,proto3,enum=agentcage.assessment.v1.AssessmentStatus" json:"status,omitempty"`
	Config        *AssessmentConfig      `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Stats         *AssessmentStats       `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentInfo) Reset() {
	*x = AssessmentInfo{}
	mi := &file_api_proto_assessment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentInfo) ProtoMessage() {}

func (x *AssessmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentInfo.ProtoReflect.Descriptor instead.
func (*AssessmentInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{10}
}

func (x *AssessmentInfo) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

func (x *AssessmentInfo) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AssessmentInfo) GetStatus() AssessmentStatus {
	if x != nil {
		return x.Status
	}
	return AssessmentStatus_ASSESSMENT_STATUS_UNSPECIFIED
}

func (x *AssessmentInfo) GetConfig() *AssessmentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *AssessmentInfo) GetStats() *AssessmentStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *AssessmentInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AssessmentInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateAssessmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *AssessmentConfig      `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	BundleRef     string                 `protobuf:"bytes,2,opt,name=bundle_ref,json=bundleRef,proto3" json:"bundle_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssessmentRequest) Reset() {
	*x = CreateAssessmentRequest{}
	mi := &file_api_proto_assessment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssessmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssessmentRequest) ProtoMessage() {}

func (x *CreateAssessmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssessmentRequest.ProtoReflect.Descriptor instead.
func (*CreateAssessmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{11}
}

func (x *CreateAssessmentRequest) GetConfig() *AssessmentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateAssessmentRequest) GetBundleRef() string {
	if x != nil {
		return x.BundleRef
	}
	return ""
}

type CreateAssessmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assessment    *AssessmentInfo        `protobuf:"bytes,1,opt,name=assessment,proto3" json:"assessment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssessmentResponse) Reset() {
	*x = CreateAssessmentResponse{}
	mi := &file_api_proto_assessment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssessmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssessmentResponse) ProtoMessage() {}

func (x *CreateAssessmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssessmentResponse.ProtoReflect.Descriptor instead.
func (*CreateAssessmentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{12}
}

func (x *CreateAssessmentResponse) GetAssessment() *AssessmentInfo {
	if x != nil {
		return x.Assessment
	}
	return nil
}

type GetAssessmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId  string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssessmentRequest) Reset() {
	*x = GetAssessmentRequest{}
	mi := &file_api_proto_assessment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssessmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssessmentRequest) ProtoMessage() {}

func (x *GetAssessmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssessmentRequest.ProtoReflect.Descriptor instead.
func (*GetAssessmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{13}
}

func (x *GetAssessmentRequest) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

type GetAssessmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assessment    *AssessmentInfo        `protobuf:"bytes,1,opt,name=assessment,proto3" json:"assessment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssessmentResponse) Reset() {
	*x = GetAssessmentResponse{}
	mi := &file_api_proto_assessment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssessmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssessmentResponse) ProtoMessage() {}

func (x *GetAssessmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssessmentResponse.ProtoReflect.Descriptor instead.
func (*GetAssessmentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{14}
}

func (x *GetAssessmentResponse) GetAssessment() *AssessmentInfo {
	if x != nil {
		return x.Assessment
	}
	return nil
}

type ListAssessmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter  AssessmentStatus       `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=agentcage.assessment.v1.AssessmentStatus" json:"status_filter,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssessmentsRequest) Reset() {
	*x = ListAssessmentsRequest{}
	mi := &file_api_proto_assessment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssessmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssessmentsRequest) ProtoMessage() {}

func (x *ListAssessmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssessmentsRequest.ProtoReflect.Descriptor instead.
func (*ListAssessmentsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{15}
}

func (x *ListAssessmentsRequest) GetStatusFilter() AssessmentStatus {
	if x != nil {
		return x.StatusFilter
	}
	return AssessmentStatus_ASSESSMENT_STATUS_UNSPECIFIED
}

func (x *ListAssessmentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAssessmentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAssessmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assessments   []*AssessmentInfo      `protobuf:"bytes,1,rep,name=assessments,proto3" json:"assessments,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssessmentsResponse) Reset() {
	*x = ListAssessmentsResponse{}
	mi := &file_api_proto_assessment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssessmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssessmentsResponse) ProtoMessage() {}

func (x *ListAssessmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssessmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAssessmentsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{16}
}

func (x *ListAssessmentsResponse) GetAssessments() []*AssessmentInfo {
	if x != nil {
		return x.Assessments
	}
	return nil
}

func (x *ListAssessmentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId  string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportRequest) Reset() {
	*x = GetReportRequest{}
	mi := &file_api_proto_assessment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportRequest) ProtoMessage() {}

func (x *GetReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportRequest.ProtoReflect.Descriptor instead.
func (*GetReportRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{17}
}

func (x *GetReportRequest) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

type GetReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportJson    []byte                 `protobuf:"bytes,1,opt,name=report_json,json=reportJson,proto3" json:"report_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportResponse) Reset() {
	*x = GetReportResponse{}
	mi := &file_api_proto_assessment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportResponse) ProtoMessage() {}

func (x *GetReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportResponse.ProtoReflect.Descriptor instead.
func (*GetReportResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{18}
}

func (x *GetReportResponse) GetReportJson() []byte {
	if x != nil {
		return x.ReportJson
	}
	return nil
}

type CancelAssessmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId  string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAssessmentRequest) Reset() {
	*x = CancelAssessmentRequest{}
	mi := &file_api_proto_assessment_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAssessmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAssessmentRequest) ProtoMessage() {}

func (x *CancelAssessmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAssessmentRequest.ProtoReflect.Descriptor instead.
func (*CancelAssessmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{19}
}

func (x *CancelAssessmentRequest) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

type CancelAssessmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAssessmentResponse) Reset() {
	*x = CancelAssessmentResponse{}
	mi := &file_api_proto_assessment_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAssessmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAssessmentResponse) ProtoMessage() {}

func (x *CancelAssessmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAssessmentResponse.ProtoReflect.Descriptor instead.
func (*CancelAssessmentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{20}
}

func (x *CancelAssessmentResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

type FinishAssessmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId  string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishAssessmentRequest) Reset() {
	*x = FinishAssessmentRequest{}
	mi := &file_api_proto_assessment_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishAssessmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishAssessmentRequest) ProtoMessage() {}

func (x *FinishAssessmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishAssessmentRequest.ProtoReflect.Descriptor instead.
func (*FinishAssessmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{21}
}

func (x *FinishAssessmentRequest) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

type FinishAssessmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishAssessmentResponse) Reset() {
	*x = FinishAssessmentResponse{}
	mi := &file_api_proto_assessment_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishAssessmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishAssessmentResponse) ProtoMessage() {}

func (x *FinishAssessmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_assessment_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishAssessmentResponse.ProtoReflect.Descriptor instead.
func (*FinishAssessmentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_assessment_proto_rawDescGZIP(), []int{22}
}

var File_api_proto_assessment_proto protoreflect.FileDescriptor

const file_api_proto_assessment_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/assessment.proto\x12\x17agentcage.assessment.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14api/proto/cage.proto\"\xe4\x01\n" +
	"\x0eCageTypeConfig\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.agentcage.cage.v1.CageTypeR\x04type\x12=\n" +
	"\bdefaults\x18\x02 \x01(\v2!.agentcage.cage.v1.ResourceLimitsR\bdefaults\x12$\n" +
	"\x0emax_batch_size\x18\x03 \x01(\x05R\fmaxBatchSize\x12<\n" +
	"\fmax_duration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\vmaxDuration\"\x9d\a\n" +
	"\x10AssessmentConfig\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x124\n" +
	"\x05scope\x18\x02 \x01(\v2\x1e.agentcage.cage.v1.TargetScopeR\x05scope\x12S\n" +
	"\x11cage_type_configs\x18\x03 \x03(\v2'.agentcage.assessment.v1.CageTypeConfigR\x0fcageTypeConfigs\x12,\n" +
	"\x12total_token_budget\x18\x04 \x01(\x03R\x10totalTokenBudget\x12<\n" +
	"\fmax_duration\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\vmaxDuration\x12=\n" +
	"\bguidance\x18\b \x01(\v2!.agentcage.assessment.v1.GuidanceR\bguidance\x12\x1d\n" +
	"\n" +
	"skip_paths\x18\t \x03(\tR\tskipPaths\x12G\n" +
	"\x04tags\x18\v \x03(\v23.agentcage.assessment.v1.AssessmentConfig.TagsEntryR\x04tags\x12Q\n" +
	"\rnotifications\x18\f \x01(\v2+.agentcage.assessment.v1.NotificationConfigR\rnotifications\x12\x12\n" +
	"\x04name\x18\r \x01(\tR\x04name\x12&\n" +
	"\x0fmax_total_cages\x18\x0e \x01(\x05R\rmaxTotalCages\x12%\n" +
	"\x0emax_iterations\x18\x11 \x01(\x05R\rmaxIterations\x12\\\n" +
	"\venvironment\x18\x12 \x03(\v2:.agentcage.assessment.v1.AssessmentConfig.EnvironmentEntryR\venvironment\x12=\n" +
	"\bworkflow\x18\x13 \x01(\v2!.agentcage.assessment.v1.WorkflowR\bworkflow\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\bWorkflow\x122\n" +
	"\x15require_plan_approval\x18\x01 \x01(\bR\x13requirePlanApproval\x120\n" +
	"\x14identify_in_requests\x18\x02 \x01(\bR\x12identifyInRequests\"\xe5\x01\n" +
	"\fPlanProposal\x12\x12\n" +
	"\x04goal\x18\x01 \x01(\tR\x04goal\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12=\n" +
	"\aactions\x18\x03 \x03(\v2#.agentcage.assessment.v1.PlanActionR\aactions\x12'\n" +
	"\x0festimated_cages\x18\x04 \x01(\x05R\x0eestimatedCages\x12)\n" +
	"\x10estimated_tokens\x18\x05 \x01(\x03R\x0festimatedTokens\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\"e\n" +
	"\n" +
	"PlanAction\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x1d\n" +
	"\n" +
	"vuln_class\x18\x02 \x01(\tR\tvulnClass\x12\x1c\n" +
	"\tobjective\x18\x03 \x01(\tR\tobjective\"n\n" +
	"\x12NotificationConfig\x12\x18\n" +
	"\awebhook\x18\x01 \x01(\tR\awebhook\x12\x1d\n" +
	"\n" +
	"on_finding\x18\x02 \x01(\bR\tonFinding\x12\x1f\n" +
	"\von_complete\x18\x03 \x01(\bR\n" +
	"onComplete\"\xbb\x01\n" +
	"\bGuidance\x12U\n" +
	"\x0eattack_surface\x18\x01 \x01(\v2..agentcage.assessment.v1.AttackSurfaceGuidanceR\rattackSurface\x12X\n" +
	"\x0fattack_strategy\x18\x03 \x01(\v2/.agentcage.assessment.v1.AttackStrategyGuidanceR\x0eattackStrategy\"z\n" +
	"\x15AttackSurfaceGuidance\x12\x1c\n" +
	"\tendpoints\x18\x01 \x03(\tR\tendpoints\x12\x1b\n" +
	"\tapi_specs\x18\x02 \x03(\tR\bapiSpecs\x12&\n" +
	"\x0flimit_to_listed\x18\x03 \x01(\bR\rlimitToListed\"]\n" +
	"\x16AttackStrategyGuidance\x12)\n" +
	"\x10known_weaknesses\x18\x01 \x03(\tR\x0fknownWeaknesses\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\"\x89\x02\n" +
	"\x0fAssessmentStats\x12\x1f\n" +
	"\vtotal_cages\x18\x01 \x01(\x05R\n" +
	"totalCages\x12!\n" +
	"\factive_cages\x18\x02 \x01(\x05R\vactiveCages\x12-\n" +
	"\x12findings_candidate\x18\x03 \x01(\x05R\x11findingsCandidate\x12-\n" +
	"\x12findings_validated\x18\x04 \x01(\x05R\x11findingsValidated\x12+\n" +
	"\x11findings_rejected\x18\x05 \x01(\x05R\x10findingsRejected\x12'\n" +
	"\x0ftokens_consumed\x18\x06 \x01(\x03R\x0etokensConsumed\"\x92\x03\n" +
	"\x0eAssessmentInfo\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12A\n" +
	"\x06status\x18\x03 \x01(\x0e2).agentcage.assessment.v1.AssessmentStatusR\x06status\x12A\n" +
	"\x06config\x18\x04 \x01(\v2).agentcage.assessment.v1.AssessmentConfigR\x06config\x12>\n" +
	"\x05stats\x18\x05 \x01(\v2(.agentcage.assessment.v1.AssessmentStatsR\x05stats\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"{\n" +
	"\x17CreateAssessmentRequest\x12A\n" +
	"\x06config\x18\x01 \x01(\v2).agentcage.assessment.v1.AssessmentConfigR\x06config\x12\x1d\n" +
	"\n" +
	"bundle_ref\x18\x02 \x01(\tR\tbundleRef\"c\n" +
	"\x18CreateAssessmentResponse\x12G\n" +
	"\n" +
	"assessment\x18\x01 \x01(\v2'.agentcage.assessment.v1.AssessmentInfoR\n" +
	"assessment\";\n" +
	"\x14GetAssessmentRequest\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\"`\n" +
	"\x15GetAssessmentResponse\x12G\n" +
	"\n" +
	"assessment\x18\x01 \x01(\v2'.agentcage.assessment.v1.AssessmentInfoR\n" +
	"assessment\"\x9d\x01\n" +
	"\x16ListAssessmentsRequest\x12N\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2).agentcage.assessment.v1.AssessmentStatusR\fstatusFilter\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x8c\x01\n" +
	"\x17ListAssessmentsResponse\x12I\n" +
	"\vassessments\x18\x01 \x03(\v2'.agentcage.assessment.v1.AssessmentInfoR\vassessments\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"7\n" +
	"\x10GetReportRequest\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\"4\n" +
	"\x11GetReportResponse\x12\x1f\n" +
	"\vreport_json\x18\x01 \x01(\fR\n" +
	"reportJson\">\n" +
	"\x17CancelAssessmentRequest\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\"8\n" +
	"\x18CancelAssessmentResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\">\n" +
	"\x17FinishAssessmentRequest\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\"\x1a\n" +
	"\x18FinishAssessmentResponse*\x97\x03\n" +
	"\x10AssessmentStatus\x12!\n" +
	"\x1dASSESSMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bASSESSMENT_STATUS_DISCOVERY\x10\x01\x12\"\n" +
	"\x1eASSESSMENT_STATUS_EXPLOITATION\x10\x02\x12 \n" +
	"\x1cASSESSMENT_STATUS_VALIDATION\x10\x03\x12$\n" +
	" ASSESSMENT_STATUS_PENDING_REVIEW\x10\x04\x12\x1e\n" +
	"\x1aASSESSMENT_STATUS_APPROVED\x10\x05\x12\x1e\n" +
	"\x1aASSESSMENT_STATUS_REJECTED\x10\x06\x12\x1c\n" +
	"\x18ASSESSMENT_STATUS_FAILED\x10\a\x12 \n" +
	"\x1cASSESSMENT_STATUS_UNREVIEWED\x10\b\x12,\n" +
	"(ASSESSMENT_STATUS_AWAITING_PLAN_APPROVAL\x10\t\x12%\n" +
	"!ASSESSMENT_STATUS_PLAN_UNAPPROVED\x10\n" +
	"2\xc8\x05\n" +
	"\x11AssessmentService\x12w\n" +
	"\x10CreateAssessment\x120.agentcage.assessment.v1.CreateAssessmentRequest\x1a1.agentcage.assessment.v1.CreateAssessmentResponse\x12n\n" +
	"\rGetAssessment\x12-.agentcage.assessment.v1.GetAssessmentRequest\x1a..agentcage.assessment.v1.GetAssessmentResponse\x12t\n" +
	"\x0fListAssessments\x12/.agentcage.assessment.v1.ListAssessmentsRequest\x1a0.agentcage.assessment.v1.ListAssessmentsResponse\x12w\n" +
	"\x10CancelAssessment\x120.agentcage.assessment.v1.CancelAssessmentRequest\x1a1.agentcage.assessment.v1.CancelAssessmentResponse\x12w\n" +
	"\x10FinishAssessment\x120.agentcage.assessment.v1.FinishAssessmentRequest\x1a1.agentcage.assessment.v1.FinishAssessmentResponse\x12b\n" +
	"\tGetReport\x12).agentcage.assessment.v1.GetReportRequest\x1a*.agentcage.assessment.v1.GetReportResponseB(Z&github.com/okedeji/agentcage/api/protob\x06proto3"

var (
	file_api_proto_assessment_proto_rawDescOnce sync.Once
	file_api_proto_assessment_proto_rawDescData []byte
)

func file_api_proto_assessment_proto_rawDescGZIP() []byte {
	file_api_proto_assessment_proto_rawDescOnce.Do(func() {
		file_api_proto_assessment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_assessment_proto_rawDesc), len(file_api_proto_assessment_proto_rawDesc)))
	})
	return file_api_proto_assessment_proto_rawDescData
}

var file_api_proto_assessment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_assessment_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_proto_assessment_proto_goTypes = []any{
	(AssessmentStatus)(0),            // 0: agentcage.assessment.v1.AssessmentStatus
	(*CageTypeConfig)(nil),           // 1: agentcage.assessment.v1.CageTypeConfig
	(*AssessmentConfig)(nil),         // 2: agentcage.assessment.v1.AssessmentConfig
	(*Workflow)(nil),                 // 3: agentcage.assessment.v1.Workflow
	(*PlanProposal)(nil),             // 4: agentcage.assessment.v1.PlanProposal
	(*PlanAction)(nil),               // 5: agentcage.assessment.v1.PlanAction
	(*NotificationConfig)(nil),       // 6: agentcage.assessment.v1.NotificationConfig
	(*Guidance)(nil),                 // 7: agentcage.assessment.v1.Guidance
	(*AttackSurfaceGuidance)(nil),    // 8: agentcage.assessment.v1.AttackSurfaceGuidance
	(*AttackStrategyGuidance)(nil),   // 9: agentcage.assessment.v1.AttackStrategyGuidance
	(*AssessmentStats)(nil),          // 10: agentcage.assessment.v1.AssessmentStats
	(*AssessmentInfo)(nil),           // 11: agentcage.assessment.v1.AssessmentInfo
	(*CreateAssessmentRequest)(nil),  // 12: agentcage.assessment.v1.CreateAssessmentRequest
	(*CreateAssessmentResponse)(nil), // 13: agentcage.assessment.v1.CreateAssessmentResponse
	(*GetAssessmentRequest)(nil),     // 14: agentcage.assessment.v1.GetAssessmentRequest
	(*GetAssessmentResponse)(nil),    // 15: agentcage.assessment.v1.GetAssessmentResponse
	(*ListAssessmentsRequest)(nil),   // 16: agentcage.assessment.v1.ListAssessmentsRequest
	(*ListAssessmentsResponse)(nil),  // 17: agentcage.assessment.v1.ListAssessmentsResponse
	(*GetReportRequest)(nil),         // 18: agentcage.assessment.v1.GetReportRequest
	(*GetReportResponse)(nil),        // 19: agentcage.assessment.v1.GetReportResponse
	(*CancelAssessmentRequest)(nil),  // 20: agentcage.assessment.v1.CancelAssessmentRequest
	(*CancelAssessmentResponse)(nil), // 21: agentcage.assessment.v1.CancelAssessmentResponse
	(*FinishAssessmentRequest)(nil),  // 22: agentcage.assessment.v1.FinishAssessmentRequest
	(*FinishAssessmentResponse)(nil), // 23: agentcage.assessment.v1.FinishAssessmentResponse
	nil,                              // 24: agentcage.assessment.v1.AssessmentConfig.TagsEntry
	nil,                              // 25: agentcage.assessment.v1.AssessmentConfig.EnvironmentEntry
	(CageType)(0),                    // 26: agentcage.cage.v1.CageType
	(*ResourceLimits)(nil),           // 27: agentcage.cage.v1.ResourceLimits
	(*durationpb.Duration)(nil),      // 28: google.protobuf.Duration
	(*TargetScope)(nil),              // 29: agentcage.cage.v1.TargetScope
	(*timestamppb.Timestamp)(nil),    // 30: google.protobuf.Timestamp
}
var file_api_proto_assessment_proto_depIdxs = []int32{
	26, // 0: agentcage.assessment.v1.CageTypeConfig.type:type_name -> agentcage.cage.v1.CageType
	27, // 1: agentcage.assessment.v1.CageTypeConfig.defaults:type_name -> agentcage.cage.v1.ResourceLimits
	28, // 2: agentcage.assessment.v1.CageTypeConfig.max_duration:type_name -> google.protobuf.Duration
	29, // 3: agentcage.assessment.v1.AssessmentConfig.scope:type_name -> agentcage.cage.v1.TargetScope
	1,  // 4: agentcage.assessment.v1.AssessmentConfig.cage_type_configs:type_name -> agentcage.assessment.v1.CageTypeConfig
	28, // 5: agentcage.assessment.v1.AssessmentConfig.max_duration:type_name -> google.protobuf.Duration
	7,  // 6: agentcage.assessment.v1.AssessmentConfig.guidance:type_name -> agentcage.assessment.v1.Guidance
	24, // 7: agentcage.assessment.v1.AssessmentConfig.tags:type_name -> agentcage.assessment.v1.AssessmentConfig.TagsEntry
	6,  // 8: agentcage.assessment.v1.AssessmentConfig.notifications:type_name -> agentcage.assessment.v1.NotificationConfig
	25, // 9: agentcage.assessment.v1.AssessmentConfig.environment:type_name -> agentcage.assessment.v1.AssessmentConfig.EnvironmentEntry
	3,  // 10: agentcage.assessment.v1.AssessmentConfig.workflow:type_name -> agentcage.assessment.v1.Workflow
	5,  // 11: agentcage.assessment.v1.PlanProposal.actions:type_name -> agentcage.assessment.v1.PlanAction
	8,  // 12: agentcage.assessment.v1.Guidance.attack_surface:type_name -> agentcage.assessment.v1.AttackSurfaceGuidance
	9,  // 13: agentcage.assessment.v1.Guidance.attack_strategy:type_name -> agentcage.assessment.v1.AttackStrategyGuidance
	0,  // 14: agentcage.assessment.v1.AssessmentInfo.status:type_name -> agentcage.assessment.v1.AssessmentStatus
	2,  // 15: agentcage.assessment.v1.AssessmentInfo.config:type_name -> agentcage.assessment.v1.AssessmentConfig
	10, // 16: agentcage.assessment.v1.AssessmentInfo.stats:type_name -> agentcage.assessment.v1.AssessmentStats
	30, // 17: agentcage.assessment.v1.AssessmentInfo.created_at:type_name -> google.protobuf.Timestamp
	30, // 18: agentcage.assessment.v1.AssessmentInfo.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 19: agentcage.assessment.v1.CreateAssessmentRequest.config:type_name -> agentcage.assessment.v1.AssessmentConfig
	11, // 20: agentcage.assessment.v1.CreateAssessmentResponse.assessment:type_name -> agentcage.assessment.v1.AssessmentInfo
	11, // 21: agentcage.assessment.v1.GetAssessmentResponse.assessment:type_name -> agentcage.assessment.v1.AssessmentInfo
	0,  // 22: agentcage.assessment.v1.ListAssessmentsRequest.status_filter:type_name -> agentcage.assessment.v1.AssessmentStatus
	11, // 23: agentcage.assessment.v1.ListAssessmentsResponse.assessments:type_name -> agentcage.assessment.v1.AssessmentInfo
	12, // 24: agentcage.assessment.v1.AssessmentService.CreateAssessment:input_type -> agentcage.assessment.v1.CreateAssessmentRequest
	14, // 25: agentcage.assessment.v1.AssessmentService.GetAssessment:input_type -> agentcage.assessment.v1.GetAssessmentRequest
	16, // 26: agentcage.assessment.v1.AssessmentService.ListAssessments:input_type -> agentcage.assessment.v1.ListAssessmentsRequest
	20, // 27: agentcage.assessment.v1.AssessmentService.CancelAssessment:input_type -> agentcage.assessment.v1.CancelAssessmentRequest
	22, // 28: agentcage.assessment.v1.AssessmentService.FinishAssessment:input_type -> agentcage.assessment.v1.FinishAssessmentRequest
	18, // 29: agentcage.assessment.v1.AssessmentService.GetReport:input_type -> agentcage.assessment.v1.GetReportRequest
	13, // 30: agentcage.assessment.v1.AssessmentService.CreateAssessment:output_type -> agentcage.assessment.v1.CreateAssessmentResponse
	15, // 31: agentcage.assessment.v1.AssessmentService.GetAssessment:output_type -> agentcage.assessment.v1.GetAssessmentResponse
	17, // 32: agentcage.assessment.v1.AssessmentService.ListAssessments:output_type -> agentcage.assessment.v1.ListAssessmentsResponse
	21, // 33: agentcage.assessment.v1.AssessmentService.CancelAssessment:output_type -> agentcage.assessment.v1.CancelAssessmentResponse
	23, // 34: agentcage.assessment.v1.AssessmentService.FinishAssessment:output_type -> agentcage.assessment.v1.FinishAssessmentResponse
	19, // 35: agentcage.assessment.v1.AssessmentService.GetReport:output_type -> agentcage.assessment.v1.GetReportResponse
	30, // [30:36] is the sub-list for method output_type
	24, // [24:30] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_api_proto_assessment_proto_init() }
func file_api_proto_assessment_proto_init() {
	if File_api_proto_assessment_proto != nil {
		return
	}
	file_api_proto_cage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_assessment_proto_rawDesc), len(file_api_proto_assessment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_assessment_proto_goTypes,
		DependencyIndexes: file_api_proto_assessment_proto_depIdxs,
		EnumInfos:         file_api_proto_assessment_proto_enumTypes,
		MessageInfos:      file_api_proto_assessment_proto_msgTypes,
	}.Build()
	File_api_proto_assessment_proto = out.File
	file_api_proto_assessment_proto_goTypes = nil
	file_api_proto_assessment_proto_depIdxs = nil
}
