// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/cage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CageType int32

const (
	CageType_CAGE_TYPE_UNSPECIFIED  CageType = 0
	CageType_CAGE_TYPE_DISCOVERY    CageType = 1
	CageType_CAGE_TYPE_VALIDATOR    CageType = 2
	CageType_CAGE_TYPE_ESCALATION   CageType = 3 // deprecated: use EXPLOITATION
	CageType_CAGE_TYPE_EXPLOITATION CageType = 4
)

// Enum value maps for CageType.
var (
	CageType_name = map[int32]string{
		0: "CAGE_TYPE_UNSPECIFIED",
		1: "CAGE_TYPE_DISCOVERY",
		2: "CAGE_TYPE_VALIDATOR",
		3: "CAGE_TYPE_ESCALATION",
		4: "CAGE_TYPE_EXPLOITATION",
	}
	CageType_value = map[string]int32{
		"CAGE_TYPE_UNSPECIFIED":  0,
		"CAGE_TYPE_DISCOVERY":    1,
		"CAGE_TYPE_VALIDATOR":    2,
		"CAGE_TYPE_ESCALATION":   3,
		"CAGE_TYPE_EXPLOITATION": 4,
	}
)

func (x CageType) Enum() *CageType {
	p := new(CageType)
	*p = x
	return p
}

func (x CageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CageType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_cage_proto_enumTypes[0].Descriptor()
}

func (CageType) Type() protoreflect.EnumType {
	return &file_api_proto_cage_proto_enumTypes[0]
}

func (x CageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CageType.Descriptor instead.
func (CageType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{0}
}

type CageState int32

const (
	CageState_CAGE_STATE_UNSPECIFIED  CageState = 0
	CageState_CAGE_STATE_PENDING      CageState = 1
	CageState_CAGE_STATE_PROVISIONING CageState = 2
	CageState_CAGE_STATE_RUNNING      CageState = 3
	CageState_CAGE_STATE_PAUSED       CageState = 4
	CageState_CAGE_STATE_TEARING_DOWN CageState = 5
	CageState_CAGE_STATE_COMPLETED    CageState = 6
	CageState_CAGE_STATE_FAILED       CageState = 7
)

// Enum value maps for CageState.
var (
	CageState_name = map[int32]string{
		0: "CAGE_STATE_UNSPECIFIED",
		1: "CAGE_STATE_PENDING",
		2: "CAGE_STATE_PROVISIONING",
		3: "CAGE_STATE_RUNNING",
		4: "CAGE_STATE_PAUSED",
		5: "CAGE_STATE_TEARING_DOWN",
		6: "CAGE_STATE_COMPLETED",
		7: "CAGE_STATE_FAILED",
	}
	CageState_value = map[string]int32{
		"CAGE_STATE_UNSPECIFIED":  0,
		"CAGE_STATE_PENDING":      1,
		"CAGE_STATE_PROVISIONING": 2,
		"CAGE_STATE_RUNNING":      3,
		"CAGE_STATE_PAUSED":       4,
		"CAGE_STATE_TEARING_DOWN": 5,
		"CAGE_STATE_COMPLETED":    6,
		"CAGE_STATE_FAILED":       7,
	}
)

func (x CageState) Enum() *CageState {
	p := new(CageState)
	*p = x
	return p
}

func (x CageState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CageState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_cage_proto_enumTypes[1].Descriptor()
}

func (CageState) Type() protoreflect.EnumType {
	return &file_api_proto_cage_proto_enumTypes[1]
}

func (x CageState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CageState.Descriptor instead.
func (CageState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{1}
}

type RoutingStrategy int32

const (
	RoutingStrategy_ROUTING_STRATEGY_UNSPECIFIED    RoutingStrategy = 0
	RoutingStrategy_ROUTING_STRATEGY_COST_OPTIMIZED RoutingStrategy = 1
	RoutingStrategy_ROUTING_STRATEGY_QUALITY_FIRST  RoutingStrategy = 2
	RoutingStrategy_ROUTING_STRATEGY_LATENCY_FIRST  RoutingStrategy = 3
)

// Enum value maps for RoutingStrategy.
var (
	RoutingStrategy_name = map[int32]string{
		0: "ROUTING_STRATEGY_UNSPECIFIED",
		1: "ROUTING_STRATEGY_COST_OPTIMIZED",
		2: "ROUTING_STRATEGY_QUALITY_FIRST",
		3: "ROUTING_STRATEGY_LATENCY_FIRST",
	}
	RoutingStrategy_value = map[string]int32{
		"ROUTING_STRATEGY_UNSPECIFIED":    0,
		"ROUTING_STRATEGY_COST_OPTIMIZED": 1,
		"ROUTING_STRATEGY_QUALITY_FIRST":  2,
		"ROUTING_STRATEGY_LATENCY_FIRST":  3,
	}
)

func (x RoutingStrategy) Enum() *RoutingStrategy {
	p := new(RoutingStrategy)
	*p = x
	return p
}

func (x RoutingStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoutingStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_cage_proto_enumTypes[2].Descriptor()
}

func (RoutingStrategy) Type() protoreflect.EnumType {
	return &file_api_proto_cage_proto_enumTypes[2]
}

func (x RoutingStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoutingStrategy.Descriptor instead.
func (RoutingStrategy) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{2}
}

type PatternEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatternEntry) Reset() {
	*x = PatternEntry{}
	mi := &file_api_proto_cage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatternEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatternEntry) ProtoMessage() {}

func (x *PatternEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatternEntry.ProtoReflect.Descriptor instead.
func (*PatternEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{0}
}

func (x *PatternEntry) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *PatternEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TargetScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []string               `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Ports         []string               `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	Paths         []string               `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	Extras        []string               `protobuf:"bytes,4,rep,name=extras,proto3" json:"extras,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetScope) Reset() {
	*x = TargetScope{}
	mi := &file_api_proto_cage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetScope) ProtoMessage() {}

func (x *TargetScope) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetScope.ProtoReflect.Descriptor instead.
func (*TargetScope) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{1}
}

func (x *TargetScope) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *TargetScope) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *TargetScope) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *TargetScope) GetExtras() []string {
	if x != nil {
		return x.Extras
	}
	return nil
}

type ResourceLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vcpus         int32                  `protobuf:"varint,1,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_api_proto_cage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceLimits) GetVcpus() int32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *ResourceLimits) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

type TimeLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxDuration   *durationpb.Duration   `protobuf:"bytes,1,opt,name=max_duration,json=maxDuration,proto3" json:"max_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeLimits) Reset() {
	*x = TimeLimits{}
	mi := &file_api_proto_cage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeLimits) ProtoMessage() {}

func (x *TimeLimits) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeLimits.ProtoReflect.Descriptor instead.
func (*TimeLimits) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{3}
}

func (x *TimeLimits) GetMaxDuration() *durationpb.Duration {
	if x != nil {
		return x.MaxDuration
	}
	return nil
}

type RateLimits struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestsPerSecond int32                  `protobuf:"varint,1,opt,name=requests_per_second,json=requestsPerSecond,proto3" json:"requests_per_second,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RateLimits) Reset() {
	*x = RateLimits{}
	mi := &file_api_proto_cage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimits) ProtoMessage() {}

func (x *RateLimits) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimits.ProtoReflect.Descriptor instead.
func (*RateLimits) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{4}
}

func (x *RateLimits) GetRequestsPerSecond() int32 {
	if x != nil {
		return x.RequestsPerSecond
	}
	return 0
}

type LLMGatewayConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TokenBudget     int64                  `protobuf:"varint,1,opt,name=token_budget,json=tokenBudget,proto3" json:"token_budget,omitempty"`
	RoutingStrategy RoutingStrategy        `protobuf:"varint,2,opt,name=routing_strategy,json=routingStrategy,proto3,enum=agentcage.cage.v1.RoutingStrategy" json:"routing_strategy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LLMGatewayConfig) Reset() {
	*x = LLMGatewayConfig{}
	mi := &file_api_proto_cage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMGatewayConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMGatewayConfig) ProtoMessage() {}

func (x *LLMGatewayConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMGatewayConfig.ProtoReflect.Descriptor instead.
func (*LLMGatewayConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{5}
}

func (x *LLMGatewayConfig) GetTokenBudget() int64 {
	if x != nil {
		return x.TokenBudget
	}
	return 0
}

func (x *LLMGatewayConfig) GetRoutingStrategy() RoutingStrategy {
	if x != nil {
		return x.RoutingStrategy
	}
	return RoutingStrategy_ROUTING_STRATEGY_UNSPECIFIED
}

type PayloadProxyConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	JudgeEndpoint       string                 `protobuf:"bytes,1,opt,name=judge_endpoint,json=judgeEndpoint,proto3" json:"judge_endpoint,omitempty"`
	JudgeConfidence     float64                `protobuf:"fixed64,2,opt,name=judge_confidence,json=judgeConfidence,proto3" json:"judge_confidence,omitempty"`
	JudgeTimeoutSeconds int32                  `protobuf:"varint,3,opt,name=judge_timeout_seconds,json=judgeTimeoutSeconds,proto3" json:"judge_timeout_seconds,omitempty"`
	ExtraBlock          []*PatternEntry        `protobuf:"bytes,4,rep,name=extra_block,json=extraBlock,proto3" json:"extra_block,omitempty"`
	ExtraFlag           []*PatternEntry        `protobuf:"bytes,5,rep,name=extra_flag,json=extraFlag,proto3" json:"extra_flag,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PayloadProxyConfig) Reset() {
	*x = PayloadProxyConfig{}
	mi := &file_api_proto_cage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadProxyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadProxyConfig) ProtoMessage() {}

func (x *PayloadProxyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadProxyConfig.ProtoReflect.Descriptor instead.
func (*PayloadProxyConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{6}
}

func (x *PayloadProxyConfig) GetJudgeEndpoint() string {
	if x != nil {
		return x.JudgeEndpoint
	}
	return ""
}

func (x *PayloadProxyConfig) GetJudgeConfidence() float64 {
	if x != nil {
		return x.JudgeConfidence
	}
	return 0
}

func (x *PayloadProxyConfig) GetJudgeTimeoutSeconds() int32 {
	if x != nil {
		return x.JudgeTimeoutSeconds
	}
	return 0
}

func (x *PayloadProxyConfig) GetExtraBlock() []*PatternEntry {
	if x != nil {
		return x.ExtraBlock
	}
	return nil
}

func (x *PayloadProxyConfig) GetExtraFlag() []*PatternEntry {
	if x != nil {
		return x.ExtraFlag
	}
	return nil
}

type CageConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId    string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	Type            CageType               `protobuf:"varint,2,opt,name=type,proto3,enum=agentcage.cage.v1.CageType" json:"type,omitempty"`
	Scope           *TargetScope           `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Resources       *ResourceLimits        `protobuf:"bytes,4,opt,name=resources,proto3" json:"resources,omitempty"`
	TimeLimits      *TimeLimits            `protobuf:"bytes,5,opt,name=time_limits,json=timeLimits,proto3" json:"time_limits,omitempty"`
	RateLimits      *RateLimits            `protobuf:"bytes,6,opt,name=rate_limits,json=rateLimits,proto3" json:"rate_limits,omitempty"`
	LlmGateway      *LLMGatewayConfig      `protobuf:"bytes,7,opt,name=llm_gateway,json=llmGateway,proto3,oneof" json:"llm_gateway,omitempty"`
	ProxyConfig     *PayloadProxyConfig    `protobuf:"bytes,8,opt,name=proxy_config,json=proxyConfig,proto3" json:"proxy_config,omitempty"`
	ParentFindingId string                 `protobuf:"bytes,9,opt,name=parent_finding_id,json=parentFindingId,proto3" json:"parent_finding_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CageConfig) Reset() {
	*x = CageConfig{}
	mi := &file_api_proto_cage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CageConfig) ProtoMessage() {}

func (x *CageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CageConfig.ProtoReflect.Descriptor instead.
func (*CageConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{7}
}

func (x *CageConfig) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

func (x *CageConfig) GetType() CageType {
	if x != nil {
		return x.Type
	}
	return CageType_CAGE_TYPE_UNSPECIFIED
}

func (x *CageConfig) GetScope() *TargetScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *CageConfig) GetResources() *ResourceLimits {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *CageConfig) GetTimeLimits() *TimeLimits {
	if x != nil {
		return x.TimeLimits
	}
	return nil
}

func (x *CageConfig) GetRateLimits() *RateLimits {
	if x != nil {
		return x.RateLimits
	}
	return nil
}

func (x *CageConfig) GetLlmGateway() *LLMGatewayConfig {
	if x != nil {
		return x.LlmGateway
	}
	return nil
}

func (x *CageConfig) GetProxyConfig() *PayloadProxyConfig {
	if x != nil {
		return x.ProxyConfig
	}
	return nil
}

func (x *CageConfig) GetParentFindingId() string {
	if x != nil {
		return x.ParentFindingId
	}
	return ""
}

type CageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CageId        string                 `protobuf:"bytes,1,opt,name=cage_id,json=cageId,proto3" json:"cage_id,omitempty"`
	AssessmentId  string                 `protobuf:"bytes,2,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	Type          CageType               `protobuf:"varint,3,opt,name=type,proto3,enum=agentcage.cage.v1.CageType" json:"type,omitempty"`
	State         CageState              `protobuf:"varint,4,opt,name=state,proto3,enum=agentcage.cage.v1.CageState" json:"state,omitempty"`
	Config        *CageConfig            `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CageInfo) Reset() {
	*x = CageInfo{}
	mi := &file_api_proto_cage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CageInfo) ProtoMessage() {}

func (x *CageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CageInfo.ProtoReflect.Descriptor instead.
func (*CageInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{8}
}

func (x *CageInfo) GetCageId() string {
	if x != nil {
		return x.CageId
	}
	return ""
}

func (x *CageInfo) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

func (x *CageInfo) GetType() CageType {
	if x != nil {
		return x.Type
	}
	return CageType_CAGE_TYPE_UNSPECIFIED
}

func (x *CageInfo) GetState() CageState {
	if x != nil {
		return x.State
	}
	return CageState_CAGE_STATE_UNSPECIFIED
}

func (x *CageInfo) GetConfig() *CageConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CageInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CageInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *CageInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateCageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *CageConfig            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCageRequest) Reset() {
	*x = CreateCageRequest{}
	mi := &file_api_proto_cage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCageRequest) ProtoMessage() {}

func (x *CreateCageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCageRequest.ProtoReflect.Descriptor instead.
func (*CreateCageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{9}
}

func (x *CreateCageRequest) GetConfig() *CageConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateCageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cage          *CageInfo              `protobuf:"bytes,1,opt,name=cage,proto3" json:"cage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCageResponse) Reset() {
	*x = CreateCageResponse{}
	mi := &file_api_proto_cage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCageResponse) ProtoMessage() {}

func (x *CreateCageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCageResponse.ProtoReflect.Descriptor instead.
func (*CreateCageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{10}
}

func (x *CreateCageResponse) GetCage() *CageInfo {
	if x != nil {
		return x.Cage
	}
	return nil
}

type GetCageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CageId        string                 `protobuf:"bytes,1,opt,name=cage_id,json=cageId,proto3" json:"cage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCageRequest) Reset() {
	*x = GetCageRequest{}
	mi := &file_api_proto_cage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCageRequest) ProtoMessage() {}

func (x *GetCageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCageRequest.ProtoReflect.Descriptor instead.
func (*GetCageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{11}
}

func (x *GetCageRequest) GetCageId() string {
	if x != nil {
		return x.CageId
	}
	return ""
}

type GetCageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cage          *CageInfo              `protobuf:"bytes,1,opt,name=cage,proto3" json:"cage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCageResponse) Reset() {
	*x = GetCageResponse{}
	mi := &file_api_proto_cage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCageResponse) ProtoMessage() {}

func (x *GetCageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCageResponse.ProtoReflect.Descriptor instead.
func (*GetCageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{12}
}

func (x *GetCageResponse) GetCage() *CageInfo {
	if x != nil {
		return x.Cage
	}
	return nil
}

type ListCagesByAssessmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId  string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCagesByAssessmentRequest) Reset() {
	*x = ListCagesByAssessmentRequest{}
	mi := &file_api_proto_cage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCagesByAssessmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCagesByAssessmentRequest) ProtoMessage() {}

func (x *ListCagesByAssessmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCagesByAssessmentRequest.ProtoReflect.Descriptor instead.
func (*ListCagesByAssessmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{13}
}

func (x *ListCagesByAssessmentRequest) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

type ListCagesByAssessmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CageIds       []string               `protobuf:"bytes,1,rep,name=cage_ids,json=cageIds,proto3" json:"cage_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCagesByAssessmentResponse) Reset() {
	*x = ListCagesByAssessmentResponse{}
	mi := &file_api_proto_cage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCagesByAssessmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCagesByAssessmentResponse) ProtoMessage() {}

func (x *ListCagesByAssessmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCagesByAssessmentResponse.ProtoReflect.Descriptor instead.
func (*ListCagesByAssessmentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{14}
}

func (x *ListCagesByAssessmentResponse) GetCageIds() []string {
	if x != nil {
		return x.CageIds
	}
	return nil
}

type GetCageLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CageId        string                 `protobuf:"bytes,1,opt,name=cage_id,json=cageId,proto3" json:"cage_id,omitempty"`
	TailLines     int32                  `protobuf:"varint,2,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	Serial        bool                   `protobuf:"varint,3,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCageLogsRequest) Reset() {
	*x = GetCageLogsRequest{}
	mi := &file_api_proto_cage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCageLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCageLogsRequest) ProtoMessage() {}

func (x *GetCageLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCageLogsRequest.ProtoReflect.Descriptor instead.
func (*GetCageLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{15}
}

func (x *GetCageLogsRequest) GetCageId() string {
	if x != nil {
		return x.CageId
	}
	return ""
}

func (x *GetCageLogsRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *GetCageLogsRequest) GetSerial() bool {
	if x != nil {
		return x.Serial
	}
	return false
}

type GetCageLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []string               `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	IsRunning     bool                   `protobuf:"varint,2,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCageLogsResponse) Reset() {
	*x = GetCageLogsResponse{}
	mi := &file_api_proto_cage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCageLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCageLogsResponse) ProtoMessage() {}

func (x *GetCageLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCageLogsResponse.ProtoReflect.Descriptor instead.
func (*GetCageLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{16}
}

func (x *GetCageLogsResponse) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *GetCageLogsResponse) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

type StreamCageLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CageId        string                 `protobuf:"bytes,1,opt,name=cage_id,json=cageId,proto3" json:"cage_id,omitempty"`
	TailLines     int32                  `protobuf:"varint,2,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	SourceFilter  string                 `protobuf:"bytes,3,opt,name=source_filter,json=sourceFilter,proto3" json:"source_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCageLogsRequest) Reset() {
	*x = StreamCageLogsRequest{}
	mi := &file_api_proto_cage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCageLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCageLogsRequest) ProtoMessage() {}

func (x *StreamCageLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCageLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamCageLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{17}
}

func (x *StreamCageLogsRequest) GetCageId() string {
	if x != nil {
		return x.CageId
	}
	return ""
}

func (x *StreamCageLogsRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *StreamCageLogsRequest) GetSourceFilter() string {
	if x != nil {
		return x.SourceFilter
	}
	return ""
}

type StreamCageLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	Completed     bool                   `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	CageState     string                 `protobuf:"bytes,3,opt,name=cage_state,json=cageState,proto3" json:"cage_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamCageLogsResponse) Reset() {
	*x = StreamCageLogsResponse{}
	mi := &file_api_proto_cage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamCageLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamCageLogsResponse) ProtoMessage() {}

func (x *StreamCageLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamCageLogsResponse.ProtoReflect.Descriptor instead.
func (*StreamCageLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{18}
}

func (x *StreamCageLogsResponse) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *StreamCageLogsResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *StreamCageLogsResponse) GetCageState() string {
	if x != nil {
		return x.CageState
	}
	return ""
}

type DestroyCageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CageId        string                 `protobuf:"bytes,1,opt,name=cage_id,json=cageId,proto3" json:"cage_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyCageRequest) Reset() {
	*x = DestroyCageRequest{}
	mi := &file_api_proto_cage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyCageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyCageRequest) ProtoMessage() {}

func (x *DestroyCageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyCageRequest.ProtoReflect.Descriptor instead.
func (*DestroyCageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{19}
}

func (x *DestroyCageRequest) GetCageId() string {
	if x != nil {
		return x.CageId
	}
	return ""
}

func (x *DestroyCageRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DestroyCageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyCageResponse) Reset() {
	*x = DestroyCageResponse{}
	mi := &file_api_proto_cage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyCageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyCageResponse) ProtoMessage() {}

func (x *DestroyCageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyCageResponse.ProtoReflect.Descriptor instead.
func (*DestroyCageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{20}
}

var File_api_proto_cage_proto protoreflect.FileDescriptor

const file_api_proto_cage_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/cage.proto\x12\x11agentcage.cage.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n" +
	"\fPatternEntry\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"g\n" +
	"\vTargetScope\x12\x14\n" +
	"\x05hosts\x18\x01 \x03(\tR\x05hosts\x12\x14\n" +
	"\x05ports\x18\x02 \x03(\tR\x05ports\x12\x14\n" +
	"\x05paths\x18\x03 \x03(\tR\x05paths\x12\x16\n" +
	"\x06extras\x18\x04 \x03(\tR\x06extras\"C\n" +
	"\x0eResourceLimits\x12\x14\n" +
	"\x05vcpus\x18\x01 \x01(\x05R\x05vcpus\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x05R\bmemoryMb\"J\n" +
	"\n" +
	"TimeLimits\x12<\n" +
	"\fmax_duration\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\vmaxDuration\"<\n" +
	"\n" +
	"RateLimits\x12.\n" +
	"\x13requests_per_second\x18\x01 \x01(\x05R\x11requestsPerSecond\"\x84\x01\n" +
	"\x10LLMGatewayConfig\x12!\n" +
	"\ftoken_budget\x18\x01 \x01(\x03R\vtokenBudget\x12M\n" +
	"\x10routing_strategy\x18\x02 \x01(\x0e2\".agentcage.cage.v1.RoutingStrategyR\x0froutingStrategy\"\x9c\x02\n" +
	"\x12PayloadProxyConfig\x12%\n" +
	"\x0ejudge_endpoint\x18\x01 \x01(\tR\rjudgeEndpoint\x12)\n" +
	"\x10judge_confidence\x18\x02 \x01(\x01R\x0fjudgeConfidence\x122\n" +
	"\x15judge_timeout_seconds\x18\x03 \x01(\x05R\x13judgeTimeoutSeconds\x12@\n" +
	"\vextra_block\x18\x04 \x03(\v2\x1f.agentcage.cage.v1.PatternEntryR\n" +
	"extraBlock\x12>\n" +
	"\n" +
	"extra_flag\x18\x05 \x03(\v2\x1f.agentcage.cage.v1.PatternEntryR\textraFlag\"\xaa\x04\n" +
	"\n" +
	"CageConfig\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.agentcage.cage.v1.CageTypeR\x04type\x124\n" +
	"\x05scope\x18\x03 \x01(\v2\x1e.agentcage.cage.v1.TargetScopeR\x05scope\x12?\n" +
	"\tresources\x18\x04 \x01(\v2!.agentcage.cage.v1.ResourceLimitsR\tresources\x12>\n" +
	"\vtime_limits\x18\x05 \x01(\v2\x1d.agentcage.cage.v1.TimeLimitsR\n" +
	"timeLimits\x12>\n" +
	"\vrate_limits\x18\x06 \x01(\v2\x1d.agentcage.cage.v1.RateLimitsR\n" +
	"rateLimits\x12I\n" +
	"\vllm_gateway\x18\a \x01(\v2#.agentcage.cage.v1.LLMGatewayConfigH\x00R\n" +
	"llmGateway\x88\x01\x01\x12H\n" +
	"\fproxy_config\x18\b \x01(\v2%.agentcage.cage.v1.PayloadProxyConfigR\vproxyConfig\x12*\n" +
	"\x11parent_finding_id\x18\t \x01(\tR\x0fparentFindingIdB\x0e\n" +
	"\f_llm_gateway\"\xf0\x02\n" +
	"\bCageInfo\x12\x17\n" +
	"\acage_id\x18\x01 \x01(\tR\x06cageId\x12#\n" +
	"\rassessment_id\x18\x02 \x01(\tR\fassessmentId\x12/\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1b.agentcage.cage.v1.CageTypeR\x04type\x122\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1c.agentcage.cage.v1.CageStateR\x05state\x125\n" +
	"\x06config\x18\x05 \x01(\v2\x1d.agentcage.cage.v1.CageConfigR\x06config\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"J\n" +
	"\x11CreateCageRequest\x125\n" +
	"\x06config\x18\x01 \x01(\v2\x1d.agentcage.cage.v1.CageConfigR\x06config\"E\n" +
	"\x12CreateCageResponse\x12/\n" +
	"\x04cage\x18\x01 \x01(\v2\x1b.agentcage.cage.v1.CageInfoR\x04cage\")\n" +
	"\x0eGetCageRequest\x12\x17\n" +
	"\acage_id\x18\x01 \x01(\tR\x06cageId\"B\n" +
	"\x0fGetCageResponse\x12/\n" +
	"\x04cage\x18\x01 \x01(\v2\x1b.agentcage.cage.v1.CageInfoR\x04cage\"C\n" +
	"\x1cListCagesByAssessmentRequest\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\":\n" +
	"\x1dListCagesByAssessmentResponse\x12\x19\n" +
	"\bcage_ids\x18\x01 \x03(\tR\acageIds\"d\n" +
	"\x12GetCageLogsRequest\x12\x17\n" +
	"\acage_id\x18\x01 \x01(\tR\x06cageId\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x02 \x01(\x05R\ttailLines\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\bR\x06serial\"J\n" +
	"\x13GetCageLogsResponse\x12\x14\n" +
	"\x05lines\x18\x01 \x03(\tR\x05lines\x12\x1d\n" +
	"\n" +
	"is_running\x18\x02 \x01(\bR\tisRunning\"t\n" +
	"\x15StreamCageLogsRequest\x12\x17\n" +
	"\acage_id\x18\x01 \x01(\tR\x06cageId\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x02 \x01(\x05R\ttailLines\x12#\n" +
	"\rsource_filter\x18\x03 \x01(\tR\fsourceFilter\"i\n" +
	"\x16StreamCageLogsResponse\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x12\x1c\n" +
	"\tcompleted\x18\x02 \x01(\bR\tcompleted\x12\x1d\n" +
	"\n" +
	"cage_state\x18\x03 \x01(\tR\tcageState\"E\n" +
	"\x12DestroyCageRequest\x12\x17\n" +
	"\acage_id\x18\x01 \x01(\tR\x06cageId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x15\n" +
	"\x13DestroyCageResponse*\x8d\x01\n" +
	"\bCageType\x12\x19\n" +
	"\x15CAGE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CAGE_TYPE_DISCOVERY\x10\x01\x12\x17\n" +
	"\x13CAGE_TYPE_VALIDATOR\x10\x02\x12\x18\n" +
	"\x14CAGE_TYPE_ESCALATION\x10\x03\x12\x1a\n" +
	"\x16CAGE_TYPE_EXPLOITATION\x10\x04*\xd9\x01\n" +
	"\tCageState\x12\x1a\n" +
	"\x16CAGE_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CAGE_STATE_PENDING\x10\x01\x12\x1b\n" +
	"\x17CAGE_STATE_PROVISIONING\x10\x02\x12\x16\n" +
	"\x12CAGE_STATE_RUNNING\x10\x03\x12\x15\n" +
	"\x11CAGE_STATE_PAUSED\x10\x04\x12\x1b\n" +
	"\x17CAGE_STATE_TEARING_DOWN\x10\x05\x12\x18\n" +
	"\x14CAGE_STATE_COMPLETED\x10\x06\x12\x15\n" +
	"\x11CAGE_STATE_FAILED\x10\a*\xa0\x01\n" +
	"\x0fRoutingStrategy\x12 \n" +
	"\x1cROUTING_STRATEGY_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fROUTING_STRATEGY_COST_OPTIMIZED\x10\x01\x12\"\n" +
	"\x1eROUTING_STRATEGY_QUALITY_FIRST\x10\x02\x12\"\n" +
	"\x1eROUTING_STRATEGY_LATENCY_FIRST\x10\x032\xdb\x04\n" +
	"\vCageService\x12Y\n" +
	"\n" +
	"CreateCage\x12$.agentcage.cage.v1.CreateCageRequest\x1a%.agentcage.cage.v1.CreateCageResponse\x12P\n" +
	"\aGetCage\x12!.agentcage.cage.v1.GetCageRequest\x1a\".agentcage.cage.v1.GetCageResponse\x12z\n" +
	"\x15ListCagesByAssessment\x12/.agentcage.cage.v1.ListCagesByAssessmentRequest\x1a0.agentcage.cage.v1.ListCagesByAssessmentResponse\x12\\\n" +
	"\vDestroyCage\x12%.agentcage.cage.v1.DestroyCageRequest\x1a&.agentcage.cage.v1.DestroyCageResponse\x12\\\n" +
	"\vGetCageLogs\x12%.agentcage.cage.v1.GetCageLogsRequest\x1a&.agentcage.cage.v1.GetCageLogsResponse\x12g\n" +
	"\x0eStreamCageLogs\x12(.agentcage.cage.v1.StreamCageLogsRequest\x1a).agentcage.cage.v1.StreamCageLogsResponse0\x01B(Z&github.com/okedeji/agentcage/api/protob\x06proto3"

var (
	file_api_proto_cage_proto_rawDescOnce sync.Once
	file_api_proto_cage_proto_rawDescData []byte
)

func file_api_proto_cage_proto_rawDescGZIP() []byte {
	file_api_proto_cage_proto_rawDescOnce.Do(func() {
		file_api_proto_cage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cage_proto_rawDesc), len(file_api_proto_cage_proto_rawDesc)))
	})
	return file_api_proto_cage_proto_rawDescData
}

var file_api_proto_cage_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_cage_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_proto_cage_proto_goTypes = []any{
	(CageType)(0),                         // 0: agentcage.cage.v1.CageType
	(CageState)(0),                        // 1: agentcage.cage.v1.CageState
	(RoutingStrategy)(0),                  // 2: agentcage.cage.v1.RoutingStrategy
	(*PatternEntry)(nil),                  // 3: agentcage.cage.v1.PatternEntry
	(*TargetScope)(nil),                   // 4: agentcage.cage.v1.TargetScope
	(*ResourceLimits)(nil),                // 5: agentcage.cage.v1.ResourceLimits
	(*TimeLimits)(nil),                    // 6: agentcage.cage.v1.TimeLimits
	(*RateLimits)(nil),                    // 7: agentcage.cage.v1.RateLimits
	(*LLMGatewayConfig)(nil),              // 8: agentcage.cage.v1.LLMGatewayConfig
	(*PayloadProxyConfig)(nil),            // 9: agentcage.cage.v1.PayloadProxyConfig
	(*CageConfig)(nil),                    // 10: agentcage.cage.v1.CageConfig
	(*CageInfo)(nil),                      // 11: agentcage.cage.v1.CageInfo
	(*CreateCageRequest)(nil),             // 12: agentcage.cage.v1.CreateCageRequest
	(*CreateCageResponse)(nil),            // 13: agentcage.cage.v1.CreateCageResponse
	(*GetCageRequest)(nil),                // 14: agentcage.cage.v1.GetCageRequest
	(*GetCageResponse)(nil),               // 15: agentcage.cage.v1.GetCageResponse
	(*ListCagesByAssessmentRequest)(nil),  // 16: agentcage.cage.v1.ListCagesByAssessmentRequest
	(*ListCagesByAssessmentResponse)(nil), // 17: agentcage.cage.v1.ListCagesByAssessmentResponse
	(*GetCageLogsRequest)(nil),            // 18: agentcage.cage.v1.GetCageLogsRequest
	(*GetCageLogsResponse)(nil),           // 19: agentcage.cage.v1.GetCageLogsResponse
	(*StreamCageLogsRequest)(nil),         // 20: agentcage.cage.v1.StreamCageLogsRequest
	(*StreamCageLogsResponse)(nil),        // 21: agentcage.cage.v1.StreamCageLogsResponse
	(*DestroyCageRequest)(nil),            // 22: agentcage.cage.v1.DestroyCageRequest
	(*DestroyCageResponse)(nil),           // 23: agentcage.cage.v1.DestroyCageResponse
	(*durationpb.Duration)(nil),           // 24: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),         // 25: google.protobuf.Timestamp
}
var file_api_proto_cage_proto_depIdxs = []int32{
	24, // 0: agentcage.cage.v1.TimeLimits.max_duration:type_name -> google.protobuf.Duration
	2,  // 1: agentcage.cage.v1.LLMGatewayConfig.routing_strategy:type_name -> agentcage.cage.v1.RoutingStrategy
	3,  // 2: agentcage.cage.v1.PayloadProxyConfig.extra_block:type_name -> agentcage.cage.v1.PatternEntry
	3,  // 3: agentcage.cage.v1.PayloadProxyConfig.extra_flag:type_name -> agentcage.cage.v1.PatternEntry
	0,  // 4: agentcage.cage.v1.CageConfig.type:type_name -> agentcage.cage.v1.CageType
	4,  // 5: agentcage.cage.v1.CageConfig.scope:type_name -> agentcage.cage.v1.TargetScope
	5,  // 6: agentcage.cage.v1.CageConfig.resources:type_name -> agentcage.cage.v1.ResourceLimits
	6,  // 7: agentcage.cage.v1.CageConfig.time_limits:type_name -> agentcage.cage.v1.TimeLimits
	7,  // 8: agentcage.cage.v1.CageConfig.rate_limits:type_name -> agentcage.cage.v1.RateLimits
	8,  // 9: agentcage.cage.v1.CageConfig.llm_gateway:type_name -> agentcage.cage.v1.LLMGatewayConfig
	9,  // 10: agentcage.cage.v1.CageConfig.proxy_config:type_name -> agentcage.cage.v1.PayloadProxyConfig
	0,  // 11: agentcage.cage.v1.CageInfo.type:type_name -> agentcage.cage.v1.CageType
	1,  // 12: agentcage.cage.v1.CageInfo.state:type_name -> agentcage.cage.v1.CageState
	10, // 13: agentcage.cage.v1.CageInfo.config:type_name -> agentcage.cage.v1.CageConfig
	25, // 14: agentcage.cage.v1.CageInfo.created_at:type_name -> google.protobuf.Timestamp
	25, // 15: agentcage.cage.v1.CageInfo.updated_at:type_name -> google.protobuf.Timestamp
	10, // 16: agentcage.cage.v1.CreateCageRequest.config:type_name -> agentcage.cage.v1.CageConfig
	11, // 17: agentcage.cage.v1.CreateCageResponse.cage:type_name -> agentcage.cage.v1.CageInfo
	11, // 18: agentcage.cage.v1.GetCageResponse.cage:type_name -> agentcage.cage.v1.CageInfo
	12, // 19: agentcage.cage.v1.CageService.CreateCage:input_type -> agentcage.cage.v1.CreateCageRequest
	14, // 20: agentcage.cage.v1.CageService.GetCage:input_type -> agentcage.cage.v1.GetCageRequest
	16, // 21: agentcage.cage.v1.CageService.ListCagesByAssessment:input_type -> agentcage.cage.v1.ListCagesByAssessmentRequest
	22, // 22: agentcage.cage.v1.CageService.DestroyCage:input_type -> agentcage.cage.v1.DestroyCageRequest
	18, // 23: agentcage.cage.v1.CageService.GetCageLogs:input_type -> agentcage.cage.v1.GetCageLogsRequest
	20, // 24: agentcage.cage.v1.CageService.StreamCageLogs:input_type -> agentcage.cage.v1.StreamCageLogsRequest
	13, // 25: agentcage.cage.v1.CageService.CreateCage:output_type -> agentcage.cage.v1.CreateCageResponse
	15, // 26: agentcage.cage.v1.CageService.GetCage:output_type -> agentcage.cage.v1.GetCageResponse
	17, // 27: agentcage.cage.v1.CageService.ListCagesByAssessment:output_type -> agentcage.cage.v1.ListCagesByAssessmentResponse
	23, // 28: agentcage.cage.v1.CageService.DestroyCage:output_type -> agentcage.cage.v1.DestroyCageResponse
	19, // 29: agentcage.cage.v1.CageService.GetCageLogs:output_type -> agentcage.cage.v1.GetCageLogsResponse
	21, // 30: agentcage.cage.v1.CageService.StreamCageLogs:output_type -> agentcage.cage.v1.StreamCageLogsResponse
	25, // [25:31] is the sub-list for method output_type
	19, // [19:25] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_proto_cage_proto_init() }
func file_api_proto_cage_proto_init() {
	if File_api_proto_cage_proto != nil {
		return
	}
	file_api_proto_cage_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cage_proto_rawDesc), len(file_api_proto_cage_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_cage_proto_goTypes,
		DependencyIndexes: file_api_proto_cage_proto_depIdxs,
		EnumInfos:         file_api_proto_cage_proto_enumTypes,
		MessageInfos:      file_api_proto_cage_proto_msgTypes,
	}.Build()
	File_api_proto_cage_proto = out.File
	file_api_proto_cage_proto_goTypes = nil
	file_api_proto_cage_proto_depIdxs = nil
}
