// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/proto/intervention.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InterventionService_ListInterventions_FullMethodName       = "/agentcage.intervention.v1.InterventionService/ListInterventions"
	InterventionService_GetIntervention_FullMethodName         = "/agentcage.intervention.v1.InterventionService/GetIntervention"
	InterventionService_ResolveCageIntervention_FullMethodName = "/agentcage.intervention.v1.InterventionService/ResolveCageIntervention"
	InterventionService_ResolveAssessmentReview_FullMethodName = "/agentcage.intervention.v1.InterventionService/ResolveAssessmentReview"
	InterventionService_ResolvePlanApproval_FullMethodName     = "/agentcage.intervention.v1.InterventionService/ResolvePlanApproval"
)

// InterventionServiceClient is the client API for InterventionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InterventionServiceClient interface {
	ListInterventions(ctx context.Context, in *ListInterventionsRequest, opts ...grpc.CallOption) (*ListInterventionsResponse, error)
	GetIntervention(ctx context.Context, in *GetInterventionRequest, opts ...grpc.CallOption) (*GetInterventionResponse, error)
	ResolveCageIntervention(ctx context.Context, in *ResolveCageInterventionRequest, opts ...grpc.CallOption) (*ResolveCageInterventionResponse, error)
	ResolveAssessmentReview(ctx context.Context, in *ResolveAssessmentReviewRequest, opts ...grpc.CallOption) (*ResolveAssessmentReviewResponse, error)
	ResolvePlanApproval(ctx context.Context, in *ResolvePlanApprovalRequest, opts ...grpc.CallOption) (*ResolvePlanApprovalResponse, error)
}

type interventionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInterventionServiceClient(cc grpc.ClientConnInterface) InterventionServiceClient {
	return &interventionServiceClient{cc}
}

func (c *interventionServiceClient) ListInterventions(ctx context.Context, in *ListInterventionsRequest, opts ...grpc.CallOption) (*ListInterventionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInterventionsResponse)
	err := c.cc.Invoke(ctx, InterventionService_ListInterventions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interventionServiceClient) GetIntervention(ctx context.Context, in *GetInterventionRequest, opts ...grpc.CallOption) (*GetInterventionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInterventionResponse)
	err := c.cc.Invoke(ctx, InterventionService_GetIntervention_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interventionServiceClient) ResolveCageIntervention(ctx context.Context, in *ResolveCageInterventionRequest, opts ...grpc.CallOption) (*ResolveCageInterventionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveCageInterventionResponse)
	err := c.cc.Invoke(ctx, InterventionService_ResolveCageIntervention_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interventionServiceClient) ResolveAssessmentReview(ctx context.Context, in *ResolveAssessmentReviewRequest, opts ...grpc.CallOption) (*ResolveAssessmentReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveAssessmentReviewResponse)
	err := c.cc.Invoke(ctx, InterventionService_ResolveAssessmentReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interventionServiceClient) ResolvePlanApproval(ctx context.Context, in *ResolvePlanApprovalRequest, opts ...grpc.CallOption) (*ResolvePlanApprovalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolvePlanApprovalResponse)
	err := c.cc.Invoke(ctx, InterventionService_ResolvePlanApproval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterventionServiceServer is the server API for InterventionService service.
// All implementations must embed UnimplementedInterventionServiceServer
// for forward compatibility.
type InterventionServiceServer interface {
	ListInterventions(context.Context, *ListInterventionsRequest) (*ListInterventionsResponse, error)
	GetIntervention(context.Context, *GetInterventionRequest) (*GetInterventionResponse, error)
	ResolveCageIntervention(context.Context, *ResolveCageInterventionRequest) (*ResolveCageInterventionResponse, error)
	ResolveAssessmentReview(context.Context, *ResolveAssessmentReviewRequest) (*ResolveAssessmentReviewResponse, error)
	ResolvePlanApproval(context.Context, *ResolvePlanApprovalRequest) (*ResolvePlanApprovalResponse, error)
	mustEmbedUnimplementedInterventionServiceServer()
}

// UnimplementedInterventionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInterventionServiceServer struct{}

func (UnimplementedInterventionServiceServer) ListInterventions(context.Context, *ListInterventionsRequest) (*ListInterventionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInterventions not implemented")
}
func (UnimplementedInterventionServiceServer) GetIntervention(context.Context, *GetInterventionRequest) (*GetInterventionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIntervention not implemented")
}
func (UnimplementedInterventionServiceServer) ResolveCageIntervention(context.Context, *ResolveCageInterventionRequest) (*ResolveCageInterventionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveCageIntervention not implemented")
}
func (UnimplementedInterventionServiceServer) ResolveAssessmentReview(context.Context, *ResolveAssessmentReviewRequest) (*ResolveAssessmentReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveAssessmentReview not implemented")
}
func (UnimplementedInterventionServiceServer) ResolvePlanApproval(context.Context, *ResolvePlanApprovalRequest) (*ResolvePlanApprovalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolvePlanApproval not implemented")
}
func (UnimplementedInterventionServiceServer) mustEmbedUnimplementedInterventionServiceServer() {}
func (UnimplementedInterventionServiceServer) testEmbeddedByValue()                             {}

// UnsafeInterventionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterventionServiceServer will
// result in compilation errors.
type UnsafeInterventionServiceServer interface {
	mustEmbedUnimplementedInterventionServiceServer()
}

func RegisterInterventionServiceServer(s grpc.ServiceRegistrar, srv InterventionServiceServer) {
	// If the following call panics, it indicates UnimplementedInterventionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InterventionService_ServiceDesc, srv)
}

func _InterventionService_ListInterventions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInterventionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterventionServiceServer).ListInterventions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterventionService_ListInterventions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterventionServiceServer).ListInterventions(ctx, req.(*ListInterventionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterventionService_GetIntervention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInterventionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterventionServiceServer).GetIntervention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterventionService_GetIntervention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterventionServiceServer).GetIntervention(ctx, req.(*GetInterventionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterventionService_ResolveCageIntervention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveCageInterventionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterventionServiceServer).ResolveCageIntervention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterventionService_ResolveCageIntervention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterventionServiceServer).ResolveCageIntervention(ctx, req.(*ResolveCageInterventionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterventionService_ResolveAssessmentReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAssessmentReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterventionServiceServer).ResolveAssessmentReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterventionService_ResolveAssessmentReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterventionServiceServer).ResolveAssessmentReview(ctx, req.(*ResolveAssessmentReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterventionService_ResolvePlanApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolvePlanApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterventionServiceServer).ResolvePlanApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterventionService_ResolvePlanApproval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterventionServiceServer).ResolvePlanApproval(ctx, req.(*ResolvePlanApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InterventionService_ServiceDesc is the grpc.ServiceDesc for InterventionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InterventionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentcage.intervention.v1.InterventionService",
	HandlerType: (*InterventionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListInterventions",
			Handler:    _InterventionService_ListInterventions_Handler,
		},
		{
			MethodName: "GetIntervention",
			Handler:    _InterventionService_GetIntervention_Handler,
		},
		{
			MethodName: "ResolveCageIntervention",
			Handler:    _InterventionService_ResolveCageIntervention_Handler,
		},
		{
			MethodName: "ResolveAssessmentReview",
			Handler:    _InterventionService_ResolveAssessmentReview_Handler,
		},
		{
			MethodName: "ResolvePlanApproval",
			Handler:    _InterventionService_ResolvePlanApproval_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/intervention.proto",
}
